### PR TITLE
Added bash version

### PR DESCRIPTION
**Pull request by klassiker**

### CODE REVIEW

**Comment by baurmatt** [comment]
There aren't any pictures downloaded for me :/ Can you please check this again? OS was Ubuntu 14.04, bash 4.3-7ubuntu1.5, jq 1.3-1.1ubuntu1.

**Comment by klassiker** [comment]
Sure. What's the error message (if you get one?)
Make sure the username is written correctly and please tell me where the script stops working.

**Comment by baurmatt** [comment]
The script just doesn't download the images. It shows the correct id, but the images never show up in the download folder. Sadly, there is no error/exception message at all :(

**Comment by klassiker** [comment]
wget is installed?
Try to debug the script, add echos and stuff and so on

**Comment by baurmatt** [comment]
Of course wget is installed...
Found the problem, you first create a list with all download links and download the pictures later on. Since I was trying it with a huge Instagram account from a really slow internet connection at the end of the world, I just wasn't patient enough to until the end and figured there was something wrong. Sorry about that.
Merged.

**Comment by klassiker** [comment]
Oh, okay. Maybe I should change the output to something more verbosely.
Thanks.

**Pull request merged**
